name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "1 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out source
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}:latest
          ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}:${{ github.run_id }}.${{ github.run_number }}
